---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgBBylx88z3FKNpjJyGRlL4c6qV73p/+TtKuYGLu+THCGBTzbxRjs5MHv6wvvnvzPRKGtty4wVv16VZO51CFnFP+5YH7H7ttiZImyVfDFo10aJpghJCyCxYBN1lVnqvEqlj/bLJ3aj3A25aiskwhCGIo1qSF6CxTj5cJg6TLAqLeXWXNZeQt0rA0du95sSlg1WcO9BzUWgVWSr8sft25V8yVdcn5i8W7gUeBLKT/cnwXZ1oxmvShsx1A/78wCY7BQf2cfJj/Lc+BLz3v6rXEydqXvcXcbihCBqaKhBzXW2EruZpN+zx4q0PEcwbhfUavUvzzNsMXnwiulMIcg6hxmE4EJ1VWKIUmkCyMQMPfp8Xf7SFy0KsWWlGtjyYEQ/muBNkfics/YRDy5li7ui3RlE0z4TpjJo7Bb4KUPj6WXoMXrBgf6jEYcjfib8TNTW59/UfLLd2SsuRWTf/8ro1mOFYwk+qtuxCs3D/84JqRdBhDo5ZgQiziNbTg2AAjRlEMFM4teT6UNbsVl74w6zUYC7wItGLuOOUUVFrWvbetD9uHLd986uqlNow9xXqhkDjsWerP2+5WVddJkuXws+pjSaRvr9zTcFK6JIkD6veRv4pbYaXX//fsLTfQfgdNv/MKUZAu6gKuv1S0ypKqc/i+6R7cIFT36x8COHpG4qdkV0Y5Uyj5IL3Xqiq4El8ObuKnSMi3YbCnzq0lfvgmJ3o5LJsLE+/9TB6V
    STRIPE_API_KEY: AgB5ZDbQ7DGAleJNm78OXV0UKR78R7NfuNG/+lEm8wc2nRNIy8y+bH2AlK014zcejAxlYZYaOXIJk56p/KM+MXzBN6aY9d1vEGdZ2dF41wc3zpBozHp3u72oOdV1yjqDvEVD1zvvXS7QT5EtI8AauaqH0uSXqnFvpFPDXwu88NWJFJod4ci8Jd2ZDOM/fiErPV7Upn2VwegsvXYtZG3NVMf40fmHUhyMjVEH+lDZ3ZlFsXQyKU66BF1espdmKppVMRRvYJ1EjEmy128ZBuCfsQ9UhocWiYu7zkXmikVjZ14FWC5zvkB8Zr6vxqwLKn2/aLazaCdwz/R/6l24BW1qNSpZyUkNn6qmdaPY7odxFMCESxvV3ZU9DicdgQCjsdOCuoBFfat6rlaK0XmRUjXVUoiAm/GAN+n21rS7rTS5Lrq1FVQLp7UHbkdiEYXvSie43o/lxWVGYEBSfraDyYxuYteMF0otsnKux8p6iR3JlhQUc8wtNlY6/tBjenTrnmxyuBuSVDN0xl6MlZ/sFR8k2sAyTyscUsiWVspf4PzZQoHci1etMee3xfIWzkEhABDrNAZlIFQJN1dRlAKLFhegvOywYwr5vU1fmTgBU3MknaSpWPNFKJhmoicYzXatMCWlhIDAVwUynWYpzM+DRdR9WX4htmmCwtT4qFteHfy1yHQ7JJzRX6Bhv4lSLRLtv45aiK8AFrKH4isu7MM44mvU++QD
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
